config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :orders
    resources :products do
      resources :stocks
    end

    resources :categories
  end
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  authenticated :admin_user do
    root to: "admin#index", as: :admin_root
  end

  resources :categories, only: [:show]
  resources :products, only: [:show]

  get "admin" => "admin#index"
  get "cart" => "carts#show"
  post "checkout" => "checkouts#create"
  get "success" => "checkouts#success"
  get "cancel" => "checkouts#cancel"
  post "webhooks" => "webhooks#stripe"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true

  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [50, 50]
    attachable.variant :large, resize_and_pad: [512, 512]
  end

  has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_products
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  scope :max_price, ->(price) { where('price <= ?', price) if price.present? }
  scope :min_price, ->(price) { where('price >= ?', price) if price.present? }

  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize_to_limit: [50, 50]
    attachable.variant :medium, resize_to_limit: [250, 250]
  end

  belongs_to :category
  has_many :stocks
  has_many :order_products
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :product
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!

  DAYS_OF_THE_WEEK = %w[Monday Tuesday Wednesday Thursday Friday Saturday Sunday].freeze

  def index
    @orders = Order.where(fulfilled: false).order(created_at: :desc).take(5)
    stats_service = StatsService.new
    @quick_stats = stats_service.quick_stats
    @revenue_by_day = stats_service.revenue_by_day
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show; end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @products = @category.products
                         .max_price(price_params[:max])
                         .min_price(price_params[:min])
  end

  private

  def price_params
    params.permit(:max, :min)
  end
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  def create
    cart_params = checkout_params[:cart]
    service = StripeCheckoutService.new(cart_params)
    result = service.create_session

    if result[:error]
      render json: { error: result[:error] }, status: result[:status]
    else
      render json: { url: result[:url] }
    end
  end

  def success
    render :success
  end

  def cancel
    render :cancel
  end

  private

  def checkout_params
    params.permit(cart: %i[id size quantity price name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  NUM_OF_CATEGORIES = 4

  def index
    @main_categories = Category.take(NUM_OF_CATEGORIES)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show]

  def show; end

  private

  def set_product
    @product = Product.find(params[:id])
  end
end

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
  skip_forgery_protection

  def stripe
    service = StripeWebhookService.new(request.body.read, request.env["HTTP_STRIPE_SIGNATURE"])
    result = service.process
    render json: result[:json], status: result[:status]
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/stocks_helper.rb
module Admin::StocksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/admin/index.html.erb
<div class="flex justify-between flex-wrap mt-8 w-full items-center max-w-4xl">
  <h2 class="text-2xl text-gray-800 font-medium mb-4">Daily Stats</h2>
  <div class="flex gap-10 flex-col md:flex-row justify-between w-full">
    <div class="max-w-sm rounded overflow-hidden shadow-xl bg-gradient-to-r from-gray-400 to-gray-300">
      <div class="px-6 py-4">
        <div class="font-bold text-xl mb-2 text-white">Revenue</div>
        <p class="text-white text-base">
          $<%= @quick_stats[:revenue] ? (@quick_stats[:revenue]/100.0).to_s : "0" %>
        </p>
      </div>
    </div>
    <div class="max-w-sm rounded overflow-hidden shadow-xl bg-gradient-to-r from-gray-400 to-gray-300">
      <div class="px-6 py-4">
        <div class="font-bold text-xl mb-2 text-white">Total Sales</div>
        <p class="text-white text-base">
          <%= @quick_stats[:sales] ? (@quick_stats[:sales]).to_s : "0" %>
        </p>
      </div>
    </div>
    <div class="max-w-sm rounded overflow-hidden shadow-xl bg-gradient-to-r from-gray-400 to-gray-300">
      <div class="px-6 py-4">
        <div class="font-bold text-xl mb-2 text-white">Average Sale</div>
        <p class="text-white text-base">
          $<%= @quick_stats[:avg_sale] ? (@quick_stats[:avg_sale]/100.0).to_s : "0" %>
        </p>
      </div>
    </div>
    <div class="max-w-sm rounded overflow-hidden shadow-xl bg-gradient-to-r from-gray-400 to-gray-300">
      <div class="px-6 py-4">
        <div class="font-bold text-xl mb-2 text-white">Items/Sale</div>
        <p class="text-white text-base">
          <%= @quick_stats[:per_sale].to_i %>
        </p>
      </div>
    </div>
  </div>

  <div class="my-8 w-full">
    <h2 class="text-2xl text-gray-800 font-medium mb-4">Revenue</h2>
    <div class="w-full" data-controller="dashboard" data-dashboard-revenue-value="<%= @revenue_by_day.to_json %>">
      <canvas id="revenueChart"></canvas>
    </div>
  </div>

  <div class="flex flex-col w-full">
    <h2 class="text-2xl text-gray-800 mb-4 font-medium">Recent Unfulfilled Orders</h2>
    <div class="overflow-x-auto">
      <table class="min-w-full bg-gray-100" style="border-collapse: separate; border-spacing: 0;">
      <thead>
        <tr class="text-gray-800">
          <th class="px-6 py-3 border-b-2 border-gray-200 bg-gray-100">Order ID</th>
          <th class="px-6 py-3 border-b-2 border-gray-200 bg-gray-100">Customer</th>
          <th class="px-6 py-3 border-b-2 border-gray-200 bg-gray-100">Date</th>
          <th class="px-6 py-3 border-b-2 border-gray-200 bg-gray-100">Amount</th>
        </tr>
      </thead>
      <tbody class="text-gray-700">
        <% @orders.each do |order| %>
          <tr>
            <td class="px-6 py-4 border-b border-gray-200">
              <%= link_to order.id, admin_order_path(order), class: "underline" %>
            </td>
            <td class="px-6 py-4 border-b border-gray-200">
              <%= order.customer_email %>
            </td>
            <td class="px-6 py-4 border-b border-gray-200">
              <%= order.created_at.strftime("%B %d, %Y %H:%M") %>
            </td>
            <td class="px-6 py-4 border-b border-gray-200">
              <%= (order.total/100.0).to_s %>
            </td>
          </tr>
        <% end %>
      </tbody>
      </table>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="bg-gray-800 text-white">
  <div class="max-2-6xl max-auto px-4 py-10 md:py-20">
    <div class="xl:grid xl:grid-cols-3 xl:gap-8">
      <!-- About section -->
      <div class="space-y-8 xl:col-span-1">
        <h3 class="text-sm font-semibold text-gray-200 tracking-wider uppercase">About Vk</h3>
        <p class="text-white leading-6">
          Vk is a leading online marketplace, offering a wide range of products to cater to all your needs. Our commitment ot quality and customer service ensures a great shopping experience.
        </p>
      </div>

      <!-- Quick Links -->
      <div class="mt-12 grid grid-cols-2 gap-8 xl:mt-0 xl:col-span-2">
        <div class="md:grid md:grid-cols-2 md:gap-8">
          <div>
            <h3 class="text-sm font-semibold text-gray-200 tracking wider uppercase">Quick Links</h3>
            <ul class="mt-4 space-y-4">
              <li>
                <%= link_to "Home", root_path, class: "text-base leading-6 text-white hover:text-gray-100" %>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <!-- Contact information -->
      <div class="mt-8 mb-8 md:grid md:grid-cols-2 md:gap-8">
        <div>
          <h3 class="text-sm font-semibold tracking-wider uppercase text-gray-200">
            Contact
          </h3>
          <ul class="mt-4 space-y-4">
            <li>
              <p class="text-base leading-6 text-white">
              123 Ecom Lane <br>
              E-commerce City, EC 12345
              </p>
            </li>
            <li>
              <p class="text-base leading-6 text-white">
              Email: support@ecom.com
              </p>
            </li>
            <li>
              <p class="text-base leading-6 text-white">
              Phone: (123) 456-7890
              </p>
            </li>
          </ul>
        </div>
      </div>

      <div class="border-t border-gray-700">
        <div class="max-w-6xl mx-auto px-4 py-6 md:flex md:items-center md:justify-between">
          <p class="mt-6 text-base leading-6 text-gray-400 md:mt-0 md:order-1">
          &copy; <%= Time.now.year %> Vk, Inc. All rights reserved.
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="fixed w-full top-0 bg-gray-100 z-10 py-4">
  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
    <div class="relative flex items-center justify-between h-16">
      <div class="flex-1 flex items-center justify-center sm:items-stretch sm:justify-between">
        <div class="hidden sm:flex items-center justify-center">
          <div class="flex space-x-10">
            <%= link_to 'Shop', root_path, class: "text-gray-500 hover:underline py-2 rounded-md text-md font-medium" %>
            <%= link_to 'Sign In', new_session_path(:admin), class: "text-gray-500 hover:underline py-2 rounded-md text-md font-medium" %>
          </div>
        </div>
        <div class="flex-shrink-0 flex items-center">
          <%= link_to root_path do %>
            <%= image_tag 'logo.png', class: 'block lg:hidden h-20 w-auto' %>
          <% end %>
          <%= link_to root_path do %>
            <%= image_tag 'logo.png', class: 'hidden lg:block h-20 w-auto' %>
          <% end %>
        </div>
        <div class="hidden sm:flex sml:ml-6 items-center justify-center">
          <div class="flex space-x-10">
            <%= link_to cart_path, class: "text-gray-500 hover:underline py-2 rounded-md text-md font-medium" do %>
              <%= icon 'fa-solid', 'shopping-cart' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>