config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :orders
    resources :products do
      resources :stocks
    end

    resources :categories
  end
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  authenticated :admin_user do
    root to: "admin#index", as: :admin_root
  end

  resources :categories, only: [:show]
  resources :products, only: [:show]

  get "admin" => "admin#index"
  get "cart" => "carts#show"
  post "checkout" => "checkouts#create"
  get "success" => "checkouts#success"
  get "cancel" => "checkouts#cancel"
  post "webhooks" => "webhooks#stripe"
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true

  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [50, 50]
    attachable.variant :large, resize_and_pad: [512, 512]
  end

  has_many :products
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  before_action :set_admin_category, only: %i[show edit update destroy]

  def index
    @admin_categories = Category.all
  end

  def show; end

  def new
    @admin_category = Category.new
  end

  def edit; end

  def create
    @admin_category = Category.new(admin_category_params)

    respond_to do |format|
      if @admin_category.save
        format.html { redirect_to admin_category_url(@admin_category), notice: I18n.t('admin.controllers.categories.create.success') }
        format.json { render :show, status: :created, location: @admin_category }
      else
        format.html { render :new, status: :unprocessable_entity, notice: I18n.t('admin.controllers.categories.create.failure') }
        format.json { render json: @admin_category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @admin_category.update(admin_category_params)
        format.html { redirect_to admin_category_url(@admin_category), notice: I18n.t('admin.controllers.categories.update.success') }
        format.json { render :show, status: :ok, location: @admin_category }
      else
        format.html { render :edit, status: :unprocessable_entity, notice: I18n.t('admin.controllers.categories.update.failure') }
        format.json { render json: @admin_category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @admin_category.destroy!

    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: I18n.t('admin.controllers.categories.destroy.success') }
      format.json { head :no_content }
    end
  end

  private

  def set_admin_category
    @admin_category = Category.find(params[:id])
  end

  def admin_category_params
    params.require(:category).permit(:name, :description, :image)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @products = @category.products
                         .max_price(price_params[:max])
                         .min_price(price_params[:min])
  end

  private

  def price_params
    params.permit(:max, :min)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p class="my-5">
    <strong class="block font-medium mb-1"><%= t('admin.views.category.name') %>:</strong>
    <%= category.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1"><%= t('admin.views.category.description') %>:</strong>
    <%= category.description %>
  </p>

  <% if action_name != "show" %>
    <%= link_to t('admin.views.category.show'), [:admin, category], class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to t('admin.views.category.edit'), edit_admin_category_path(category), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/admin/categories/_form.html.erb
<%= form_with(model: [:admin, admin_category], class: "contents") do |form| %>
  <% if admin_category.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= t('admin.views.category._form.errors', count: admin_category.errors.count) %>:</h2>

      <ul>
        <% admin_category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :image %>
    <%= form.file_field :image, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl"><%= t('admin.views.category.editing') %></h1>

  <%= render "form", admin_category: @admin_category %>

  <%= link_to t('admin.views.category.show'), [:admin, @admin_category], class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to t('admin.views.category.back'), admin_categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/categories/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl"><%= t('admin.views.category.categories') %></h1>
    <%= link_to t('admin.views.category.new'), new_admin_category_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div class="flex flex-col w-full">
    <div class="overlow-x-auto sm:mx-0.5 lg:mx-0.5">
      <div class="py-2 inline-block min-w-full">
        <div class="overflow-x-auto">
          <table class="min-w-full overflow-x-scroll">
            <thead class="bg-white border-b">
              <tr>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left"></th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                  <%= t('admin.views.category.name') %>
                </th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                  <%= t('admin.views.category.description') %>
                </th>
              </tr>
            </thead>
            <tbody>
              <% @admin_categories.each do |category|%>
                <tr class="bg-gray-50 border-b">
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800">
                    <%= category.image.present? ? image_tag(category.image.variant(:thumb)) : image_tag("https://via.placeholder.com/50")  %>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800 underline">
                    <%= link_to category.name, edit_admin_category_path(category)%>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800">
                    <%= category.description%>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl"><%= t('admin.views.category.new') %></h1>

  <%= render "form", admin_category: @admin_category %>

  <%= link_to t('admin.views.category.back'), admin_categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/categories/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @admin_category %>

    <%= link_to t('admin.views.category.edit'), edit_admin_category_path(@admin_category), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to t('admin.views.category.destroy'), admin_category_path(@admin_category), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to t('admin.views.category.back'), admin_categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>